version: '3.1'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes

  httpbin:
    image: kennethreitz/httpbin
    restart: always
    ports:
      - 2345:80

  gateway:
    image: apron/gateway
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8082:8082
    volumes:
      - ./logs:/app/logs/
    environment:
      - PROXY_PORT=8080
      - ADMIN_ADDR=0.0.0.0:8082
      - REDIS_SERVER=redis:6379
    depends_on:
      - redis
